# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
# This job verifies, that it contains always the current content
# and also pushes the any necessary updates
name: Check dist

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 12.x
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run prepare

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            echo "dist=outdated" >> $GITHUB_ENV
          else
            echo "dist=current" >> $GITHUB_ENV
          fi
        id: diff

      - name: Push changes to dist/
        if: ${{ github.repository == 'pmd/pmd-github-action' && github.event_name == 'push' && env.dist == 'outdated' }}
        run: |
          git config --local user.email "pmd-bot@users.noreply.github.com"
          git config --local user.name "GitHub Actions (pmd-bot)"
          git fetch origin main && git merge --ff-only origin/main
          git add dist && git commit -m 'Updated dist' && git push origin main
